##FredMFNRogers | paparseTHREAT version 1.0 | 2022

##This program is used to ingest raw Palo Alto threat logs and output them to a human readable format.

##REF = "https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/threat-log-fields"

##The following variables are currently not in use per personal preference: cloudWildFireSubType_value, XFF_value, referrerURLFilteringSubType_value, emailSender_value, emailRecipient_value, reportIDWildFireSubType_value, sourceVM_value, destinationVM_value, HTTPMethod_value, TunnelID_value, IMEI_value, parentSessionID_value, TunnelType_value, ThreatCategory_value, ContentVersion_value. Feel free to modify this code to meet your own needs.


rcvTime_msg="Log Receive Time:                          "
firewallSN_msg="Firewall Serial Number:                    "
logType_msg="Type of Palo Alto Log:                     "
threatType_msg="Threat/Content Type:                       "
logGenTime_msg="Log Generated Time:                        "
srcIP_msg="Source IP Address:                         "
dstIP_msg="Destination IP Address:                    "
NATsrcIP_msg="NAT'd Source IP Address:                   "
NATdstIP_msg="NAT'd Destination IP Address:              "
ruleName_msg="Rule Name:                                 "
srcUser_msg="Source User:                               "
dstUser_msg="Destination User:                          "
sessionApplication_msg="Session Application:                       "
sessionVirtualZone_msg="Session Virtual System:                    "
srcZone_msg="Source Zone:                               "
dstZone_msg="Destination Zone:                          "
inboundInterface_msg="Inbound Interface:                         "
outboundInterface_msg="Outbound Interface:                        "
logAction_msg="Log Action:                                "
sessionID_msg="Session ID:                                "
repeatCount_msg="Repeat Count:                              "
srcPort_msg="Source Port:                               "
dstPort_msg="Destination Port:                          "
NATsrcPort_msg="NAT'd Source Port:                         "
NATdstPort_msg="NAT'd Destination Port:                    "
flags_msg="Flags:                                     "
##the Flags will need to be determined by parsing the value then using a case switch in final program
protocol_msg="IP Protocol:                               "
protocolAction_msg="ACTION:                                    "
URLfilename_msg="URL filename:                              "
threatID_msg="Threat ID:                                 "
category_msg="Category:                                  "
severity_msg="Severity:                                  "
direction_msg="Traffic Direction:                         "
sequenceNumber_msg="Sequence Number:                           "
srcCountry_msg="Source Country:                            "
dstCountry_msg="Destination Country:                       "
URLcontentType_msg="URL Content Type:                          "
pcapID_msg="pcap ID:                                    "
fileDigest_msg="File Digest:                               "
URLindex_msg="URL Index:                                   "
User_Agent_msg="User\-Agent:                               "
fileType_msg="File Type:                               "
echo "Which Palo Alto log would you like parsed out? (Remember to start copying after the pipes beginning with the date you see)"
read paloAltoLog
echo "Saving your log to input.csv..."
echo $paloAltoLog > ./input.csv 
#begin while loop using comma as input field separator to parse the csv Palo Alto log
IFS=","
while read -r rcvTime_value firewallSN_value logType_value threatType_value threatSubType_value logGenTime_value srcIP_value dstIP_value NATsrcIP_value NATdstIP_value ruleName_value srcUser_value dstUser_value sessionApplication_value sessionVirtualZone_value srcZone_value dstZone_value inboundInterface_value outboundInterface_value logAction_value sessionID_value trash repeatCount_value srcPort_value dstPort_value NATsrcPort_value NATdstPort_value flags_value protocol_value protocolAction_value URLfilename_value threatID_value category_value severity_value direction_value sequenceNumber_value actionFlags_value srcCountry_value dstCountry_value URLcontentType_value pcapID_value fileDigest_value cloudWildFireSubType_value URLindex_value User_Agent_value fileType_value XFF_value referrerURLFilteringSubType_value emailSender_value emailRecipient_value reportIDWildFireSubType_value reportingDevice_value sourceVM_value destinationVM_value HTTPMethod_value TunnelID_value IMEI_value parentSessionID_value TunnelType_value ThreatCategory_value ContentVersion_value
do
  echo ""
  echo "               PALO ALTO THREAT LOG PARSER... ferda"
  echo ""
  echo "     Alert Log Information:"
  echo ""
  echo "$rcvTime_msg $rcvTime_value"
  echo "$firewallSN_msg $firewallSN_value"
  echo "$logType_msg $logType_value"
  echo "$threatType_msg $threatType_value"
  echo "$logGenTime_msg $logGenTime_value"
  echo "$ruleName_msg $ruleName_value"
  echo "$sessionApplication_msg $sessionApplication_value"
  echo "$sessionVirtualZone_msg $sessionVirtualZone_value"
  echo "$inboundInterface_msg $inboundInterface_value"
  echo "$outboundInterface_msg $outboundInterface_value"
  echo "$logAction_msg $logAction_value"
  echo "$sessionID_msg $sessionID_value"
  echo "$repeatCount_msg $repeatCount_value"
  echo "$flags_msg $flags_value"
  echo "$protocol_msg $protocol_value"
  echo "$protocolAction_msg $protocolAction_value"
  echo ""
  echo "     Source Information:"
  echo ""
  echo "$srcUser_msg $srcUser_value"
  echo "$srcZone_msg $srcZone_value"  
  echo "$srcIP_msg $srcIP_value"
  echo "$NATsrcIP_msg $NATsrcIP_value"
  echo "$srcPort_msg $srcPort_value"
  echo "$NATsrcPort_msg $NATsrcPort_value"
  echo "$srcCountry_msg $srcCountry_value"
  echo ""
  echo "     Destination Information:"
  echo ""
  echo "$dstUser_msg $dstUser_value"
  echo "$dstZone_msg $dstZone_value"
  echo "$dstIP_msg $dstIP_value"
  echo "$NATdstIP_msg $NATdstIP_value"
  echo "$dstPort_msg $dstPort_value"
  echo "$NATdstPort_msg $NATdstPort_value"
  echo "$dstCountry_msg $dstCountry_value"
  echo ""
  echo "     Connection Information:"
  echo ""
  echo "$URLfilename_msg $URLfilename_value"
  echo "$threatID_msg $threatID_value"
  echo "$category_msg $category_value"
  echo "$severity_msg $severity_value"
  echo "$URLindex_msg $URLindex_value"
  echo "$User_Agent_msg $User_Agent_value"
  echo "$direction_msg $direction_value"
  echo "$sequenceNumber_msg $sequenceNumber_value"
  echo "$pcapID_msg $pcapID_value"
  echo "$fileDigest_msg $fileDigest_value"
  echo "$URLcontentType_msg $URLcontentType_value"
  echo "$fileType_msg $fileType_value"
  done < <(cat input.csv)
